# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-10 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_auto_20200310_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profilename',
            new_name='profile_name',
        ),
    ]
